#!/usr/bin/env python3
"""
Generate MON_CALLS.md from metadata/mon_registry.json and source code.

Usage:
    python3 tools/generate_mon_calls.py
    python3 tools/generate_mon_calls.py --output custom_path.md
"""

import json
import sys
import os
from datetime import datetime
from pathlib import Path

class MonCallDocGenerator:
    def __init__(self, metadata_file="metadata/mon_registry.json"):
        self.metadata_file = metadata_file
        self.handlers = []
        self.summary = {}
        self.load_metadata()

    def load_metadata(self):
        """Load handler metadata from JSON."""
        try:
            with open(self.metadata_file, 'r') as f:
                data = json.load(f)
                self.handlers = data.get('handlers', [])
                self.summary = data.get('summary', {})
        except FileNotFoundError:
            print(f"Error: {self.metadata_file} not found", file=sys.stderr)
            sys.exit(1)
        except json.JSONDecodeError as e:
            print(f"Error parsing JSON: {e}", file=sys.stderr)
            sys.exit(1)

    def generate_header(self):
        """Generate document header."""
        return f"""# MON Calls - Complete Reference

> Auto-generated from `metadata/mon_registry.json`
> Last updated: {datetime.now().strftime('%Y-%m-%d %H:%M:%S')}

**Note**: This document is regenerated by `tools/generate_mon_calls.py`. Edit `metadata/mon_registry.json` to update.

## Quick Statistics

- **Total MON calls**: {self.summary.get('total_handlers', 0)}
- **Validated** ✅: {self.summary.get('validated', 0)}
- **In Progress** 🔶: {self.summary.get('in_progress', 0)}
- **Not Implemented** ❌: {self.summary.get('not_implemented', 0)}

## Implementation Status

| Status | Count | Meaning |
|--------|-------|---------|
| ✅ VALIDATED | {self.summary.get('validated', 0)} | Fully tested, working |
| 🔶 IN_PROGRESS | {self.summary.get('in_progress', 0)} | Partial, may need fixes |
| ❌ NOT_IMPLEMENTED | {self.summary.get('not_implemented', 0)} | Stub only |

---

## By Status

### ✅ VALIDATED ({self.summary.get('validated', 0)})

| # | Name | Class | ND-100 | ND-500 | Tests |
|---|------|-------|--------|--------|-------|
"""

    def generate_status_section(self, status):
        """Generate section for handlers with given status."""
        filtered = [h for h in self.handlers if h.get('status') == status]
        if not filtered:
            return ""

        content = ""
        for h in sorted(filtered, key=lambda x: x.get('decimal', 0)):
            mon_num = h.get('mon_number', '?')
            nd100 = "✓" if h.get('nd100_compat') else "✗"
            nd500 = "✓" if h.get('nd500_compat') else "✗"
            tests = len(h.get('test_cases', []))
            content += f"| {mon_num} | {h.get('name', '?')} | {h.get('class', '?')} | {nd100} | {nd500} | {tests} |\n"

        return content + "\n"

    def generate_by_class(self):
        """Group handlers by class."""
        classes = {}
        for h in self.handlers:
            cls = h.get('class', 'Unknown')
            if cls not in classes:
                classes[cls] = []
            classes[cls].append(h)

        content = "## By Class\n\n"

        for cls in sorted(classes.keys()):
            handlers = classes[cls]
            stats = {
                'total': len(handlers),
                'validated': len([h for h in handlers if h.get('status') == 'VALIDATED']),
            }

            content += f"### {cls} ({stats['total']} total, {stats['validated']} validated)\n\n"
            content += "| # | Name | Status |\n"
            content += "|---|------|--------|\n"

            for h in sorted(handlers, key=lambda x: x.get('decimal', 0)):
                status_sym = {'VALIDATED': '✅', 'IN_PROGRESS': '🔶', 'NOT_IMPLEMENTED': '❌'}.get(h.get('status'), '?')
                content += f"| {h.get('mon_number', '?')} | {h.get('name', '?')} | {status_sym} |\n"

            content += "\n"

        return content

    def generate_handler_details(self):
        """Generate detailed handler reference."""
        content = "## Handler Details\n\n"

        for h in sorted(self.handlers, key=lambda x: x.get('decimal', 0)):
            mon_num = h.get('mon_number', '?')
            name = h.get('name', '?')
            status = h.get('status', 'UNKNOWN')
            status_sym = {'VALIDATED': '✅', 'IN_PROGRESS': '🔶', 'NOT_IMPLEMENTED': '❌'}.get(status, '?')

            content += f"\n### {mon_num} — {name} {status_sym}\n\n"

            if h.get('description'):
                content += f"{h.get('description')}\n\n"

            if h.get('source_file'):
                content += f"**File**: `{h.get('source_file')}`\n\n"

            tests = h.get('test_cases', [])
            if tests:
                content += f"**Tests**: {', '.join(tests)}\n\n"

            refs = h.get('references', [])
            if refs:
                content += f"**References**:\n"
                for ref in refs:
                    content += f"- {ref}\n"
                content += "\n"

        return content

    def generate(self, output_file="docs/MON_CALLS.md"):
        """Generate complete MON_CALLS.md document."""
        print(f"Generating {output_file}...", file=sys.stderr)

        content = ""
        content += self.generate_header()
        content += self.generate_status_section('VALIDATED')
        content += f"\n### 🔶 IN_PROGRESS ({self.summary.get('in_progress', 0)})\n\n"
        content += self.generate_status_section('IN_PROGRESS')
        content += f"\n### ❌ NOT_IMPLEMENTED ({self.summary.get('not_implemented', 0)})\n\n"
        content += self.generate_status_section('NOT_IMPLEMENTED')
        content += self.generate_by_class()
        content += self.generate_handler_details()

        # Write output
        os.makedirs(os.path.dirname(output_file) or '.', exist_ok=True)
        with open(output_file, 'w') as f:
            f.write(content)

        print(f"✓ Generated {output_file} ({len(content)} bytes)", file=sys.stderr)
        return output_file

if __name__ == '__main__':
    import argparse

    parser = argparse.ArgumentParser(description='Generate MON_CALLS.md documentation')
    parser.add_argument('--metadata', default='metadata/mon_registry.json',
                       help='Metadata JSON file')
    parser.add_argument('--output', default='docs/MON_CALLS.md',
                       help='Output markdown file')

    args = parser.parse_args()

    gen = MonCallDocGenerator(args.metadata)
    gen.generate(args.output)
